import type { Expense, Invoice, ParcelExpedition, Trip } from '@/contexts/AppContext';
import {
  COMPANY_CONTACT,
  COMPANY_NAME,
  COMPANY_TAGLINE,
  TRUCK_LOGO_SVG_MARK,
} from '@/lib/invoice-branding';
import { escapePdfHtml, formatPdfDate } from '@/lib/pdf-print';
import { formatTripStatusFr } from '@/lib/sync-utils';

const S = {
  muted: '#64748b',
  border: '#e2e8f0',
  ink: '#0f172a',
  accent: '#2563eb',
};

function fcfa(n: number, max = 0): string {
  return n.toLocaleString('fr-FR', { maximumFractionDigits: max });
}

function parcelClientsSummary(pe: ParcelExpedition): string {
  const raw = pe.lots.map((l) => l.clients?.trim()).filter(Boolean) as string[];
  const uniq = [...new Set(raw)];
  return uniq.length ? uniq.join(', ') : '—';
}

interface ParsedOrderInvoiceNotes {
  reference?: string;
  rows: Array<{ libelle: string; details?: string; montant?: string }>;
  isAutoGenerated: boolean;
}

function parseOrderInvoiceNotes(notes?: string): ParsedOrderInvoiceNotes {
  const lines = (notes ?? '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);

  const rows: ParsedOrderInvoiceNotes['rows'] = [];
  let reference: string | undefined;
  let isAutoGenerated = lines.length > 0;

  for (const line of lines) {
    const commande = line.match(/^Commande\s+(.+)$/i);
    if (commande) {
      reference = commande[1].trim();
      continue;
    }

    const marchandise = line.match(/^Marchandise\s*:\s*(.+)$/i);
    if (marchandise) {
      rows.push({ libelle: 'Marchandise', montant: marchandise[1].trim() });
      continue;
    }

    const livraison = line.match(/^Livraison\s+(.+?)\s+—\s+transport\s*:\s*([^(]+?)(?:\s*\((.+)\))?$/i);
    if (livraison) {
      rows.push({
        libelle: `Transport — ${livraison[1].trim()}`,
        montant: livraison[2].trim(),
        details: livraison[3]?.trim(),
      });
      continue;
    }

    isAutoGenerated = false;
  }

  return { reference, rows, isAutoGenerated };
}

function totalsLine(label: string, value: string, bold = false, color?: string): string {
  return `<div style="display:flex;justify-content:space-between;gap:12px;padding:4px 0;font-size:9pt;${bold ? 'font-weight:700;font-size:10pt;padding-top:6px;margin-top:4px;border-top:1px solid ${S.border};' : ''}">
    <span style="color:${S.muted};">${label}</span>
    <span style="color:${color ?? S.ink};font-weight:${bold ? 700 : 600};white-space:nowrap;">${value}</span>
  </div>`;
}

export function buildSingleInvoicePdfInnerHtml(opts: {
  invoice: Invoice;
  dejaPaye: number;
  resteAPayer: number;
  trip?: Trip;
  expense?: Expense;
  parcelExpedition?: ParcelExpedition | null;
  driver?: { prenom: string; nom: string; telephone?: string } | null;
  fournisseurNom?: string | null;
  clientLabel?: string | null;
  getTruckLabel: (id: string) => string;
}): string {
  const {
    invoice,
    dejaPaye,
    resteAPayer,
    trip,
    expense,
    parcelExpedition,
    driver,
    fournisseurNom,
    clientLabel,
    getTruckLabel,
  } = opts;

  const statusLabel =
    resteAPayer <= 0.01 ? 'Payée' : dejaPaye > 0 ? 'Paiement partiel' : 'En attente';
  const statusBg = resteAPayer <= 0.01 ? '#dcfce7' : dejaPaye > 0 ? '#dbeafe' : '#fef9c3';
  const statusFg = resteAPayer <= 0.01 ? '#166534' : dejaPaye > 0 ? '#1d4ed8' : '#a16207';

  const partyLabel = expense ? 'Fournisseur' : 'Client';
  const partyName = expense
    ? escapePdfHtml(fournisseurNom || '—')
    : escapePdfHtml(
        clientLabel ||
          invoice.factureClientLibelle ||
          (trip ? trip.client : null) ||
          (parcelExpedition ? parcelClientsSummary(parcelExpedition) : null) ||
          '—',
      );

  let prestationTitle = 'Prestation';
  let prestationMain = '—';
  let prestationSub = '';
  let extraRows = '';

  if (trip) {
    prestationTitle = 'Transport';
    prestationMain = escapePdfHtml(`${trip.origine} → ${trip.destination}`);
    const sub: string[] = [];
    if (driver) sub.push(`Chauffeur : ${escapePdfHtml(`${driver.prenom} ${driver.nom}`)}`);
    if (trip.marchandise) sub.push(`Marchandise : ${escapePdfHtml(trip.marchandise)}`);
    if (trip.tracteurId) sub.push(`Tracteur : ${escapePdfHtml(getTruckLabel(trip.tracteurId))}`);
    if (trip.remorqueuseId) sub.push(`Remorque : ${escapePdfHtml(getTruckLabel(trip.remorqueuseId))}`);
    sub.push(`Statut : ${escapePdfHtml(formatTripStatusFr(trip.statut))}`);
    sub.push(`Départ : ${formatPdfDate(trip.dateDepart)}`);
    if (trip.dateArrivee) sub.push(`Arrivée : ${formatPdfDate(trip.dateArrivee)}`);
    prestationSub = sub.join(' · ');
  } else if (expense) {
    prestationTitle = 'Dépense';
    prestationMain = escapePdfHtml(expense.description);
    prestationSub = `${escapePdfHtml(expense.categorie)}${expense.sousCategorie ? ` · ${escapePdfHtml(expense.sousCategorie)}` : ''} · ${formatPdfDate(expense.date)}`;
  } else if (parcelExpedition) {
    const pe = parcelExpedition;
    prestationTitle = 'Expédition colis';
    prestationMain = escapePdfHtml(`${pe.reference} — ${pe.origine} → ${pe.destination}`);
    const sub: string[] = [];
    if (driver) {
      sub.push(
        `Chauffeur : ${escapePdfHtml(`${driver.prenom} ${driver.nom}`)}${driver.telephone ? ` (${escapePdfHtml(driver.telephone)})` : ''}`,
      );
    }
    if (pe.tracteurId) sub.push(`Tracteur : ${escapePdfHtml(getTruckLabel(pe.tracteurId))}`);
    sub.push(`Départ : ${formatPdfDate(pe.dateDepart)}`);
    if (pe.dateArrivee?.trim()) sub.push(`Arrivée : ${formatPdfDate(pe.dateArrivee)}`);
    prestationSub = sub.join(' · ');

    const maxLots = 6;
    const lots = pe.lots.slice(0, maxLots);
    const lotRows = lots
      .map(
        (l) => `<tr>
          <td style="padding:4px 6px;border-bottom:1px solid ${S.border};font-size:8pt;">${escapePdfHtml(l.clients)}</td>
          <td style="padding:4px 6px;border-bottom:1px solid ${S.border};font-size:8pt;text-align:right;">${fcfa(l.quantite)} ${escapePdfHtml(l.unite)}</td>
          <td style="padding:4px 6px;border-bottom:1px solid ${S.border};font-size:8pt;text-align:right;">${fcfa(l.prixUnitaire)}</td>
          <td style="padding:4px 6px;border-bottom:1px solid ${S.border};font-size:8pt;text-align:right;font-weight:600;">${fcfa(l.montant)}</td>
        </tr>`,
      )
      .join('');
    const more =
      pe.lots.length > maxLots
        ? `<p style="margin:4px 0 0;font-size:7.5pt;color:${S.muted};">… et ${pe.lots.length - maxLots} autre(s) ligne(s)</p>`
        : '';
    extraRows = `
      <div style="margin-top:8px;border:1px solid ${S.border};border-radius:6px;overflow:hidden;">
        <table style="width:100%;border-collapse:collapse;">
          <thead>
            <tr style="background:#f1f5f9;">
              <th style="padding:4px 6px;text-align:left;font-size:7.5pt;color:${S.muted};">Client</th>
              <th style="padding:4px 6px;text-align:right;font-size:7.5pt;color:${S.muted};">Qté</th>
              <th style="padding:4px 6px;text-align:right;font-size:7.5pt;color:${S.muted};">PU</th>
              <th style="padding:4px 6px;text-align:right;font-size:7.5pt;color:${S.muted};">Montant</th>
            </tr>
          </thead>
          <tbody>${lotRows}</tbody>
        </table>
        ${more}
      </div>`;
  } else {
    prestationTitle = invoice.clientOrderId ? 'Commande client' : 'Prestation';
    prestationMain = escapePdfHtml(invoice.factureClientLibelle || 'Facture client');
    if (invoice.clientOrderId) {
      const parsed = parseOrderInvoiceNotes(invoice.notes);
      if (parsed.reference) {
        prestationSub = `Commande ${escapePdfHtml(parsed.reference)}`;
      }
      if (parsed.rows.length > 0) {
        const rows = parsed.rows
          .map(
            (r) => `<tr>
              <td style="padding:5px 7px;border-bottom:1px solid ${S.border};font-size:8pt;font-weight:600;color:${S.ink};">${escapePdfHtml(r.libelle)}</td>
              <td style="padding:5px 7px;border-bottom:1px solid ${S.border};font-size:7.5pt;color:${S.muted};line-height:1.35;">${r.details ? escapePdfHtml(r.details) : '—'}</td>
              <td style="padding:5px 7px;border-bottom:1px solid ${S.border};font-size:8pt;text-align:right;font-weight:700;color:${S.ink};white-space:nowrap;">${escapePdfHtml(r.montant ?? '')}</td>
            </tr>`,
          )
          .join('');
        extraRows = `
          <div style="margin-top:8px;border:1px solid ${S.border};border-radius:6px;overflow:hidden;">
            <table style="width:100%;border-collapse:collapse;">
              <thead>
                <tr style="background:#f8fafc;">
                  <th style="padding:4px 7px;text-align:left;font-size:7.5pt;color:${S.muted};">Ligne</th>
                  <th style="padding:4px 7px;text-align:left;font-size:7.5pt;color:${S.muted};">Détail</th>
                  <th style="padding:4px 7px;text-align:right;font-size:7.5pt;color:${S.muted};">Montant</th>
                </tr>
              </thead>
              <tbody>${rows}</tbody>
            </table>
          </div>`;
      } else if (invoice.notes && !parsed.isAutoGenerated) {
        prestationSub = escapePdfHtml(invoice.notes);
      }
    } else if (invoice.notes) {
      prestationSub = escapePdfHtml(invoice.notes);
    }
  }

  const remiseBlock =
    invoice.remise && invoice.remise > 0 && invoice.montantHTApresRemise
      ? totalsLine(
          `Remise (${invoice.remise} %)`,
          `-${fcfa(invoice.montantHT - invoice.montantHTApresRemise, 2)} FCFA`,
        )
      : '';

  const tvaBlock =
    invoice.tva && invoice.tva > 0
      ? totalsLine('TVA', `${fcfa(invoice.tva, 2)} FCFA`)
      : '';
  const tpsBlock =
    invoice.tps && invoice.tps > 0
      ? totalsLine('TPS', `${fcfa(invoice.tps, 2)} FCFA`)
      : '';

  const orderNotes = invoice.clientOrderId ? parseOrderInvoiceNotes(invoice.notes) : null;
  const shouldShowNotes =
    Boolean(invoice.notes) && !(orderNotes?.isAutoGenerated && orderNotes.rows.length > 0);
  const notesBlock = shouldShowNotes
    ? `<div style="margin-top:8px;padding:8px 10px;background:#f8fafc;border-radius:6px;border:1px solid ${S.border};">
        <p style="margin:0 0 2px;font-size:7.5pt;font-weight:700;color:${S.muted};text-transform:uppercase;">Remarques</p>
        <p style="margin:0;font-size:8.5pt;color:${S.ink};line-height:1.4;">${escapePdfHtml(invoice.notes)}</p>
      </div>`
    : '';

  return `
    <div class="pdf-no-break" style="width:100%;">
      <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px;padding:10px 12px;background:linear-gradient(135deg,#f8fafc,#eff6ff);border:1px solid ${S.border};border-radius:10px;">
        <div style="display:flex;align-items:center;gap:10px;min-width:0;">
          <div style="width:44px;height:44px;border-radius:9px;background:linear-gradient(135deg,#4f46e5,#2563eb);color:#fff;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
            ${TRUCK_LOGO_SVG_MARK}
          </div>
          <div style="min-width:0;">
            <div style="font-size:12pt;font-weight:800;color:${S.ink};letter-spacing:-0.02em;">${COMPANY_NAME}</div>
            <p style="margin:2px 0 0;font-size:7.5pt;color:${S.muted};">${COMPANY_TAGLINE}</p>
            <p style="margin:1px 0 0;font-size:7.5pt;color:${S.muted};">${COMPANY_CONTACT}</p>
          </div>
        </div>
        <div style="text-align:right;flex-shrink:0;">
          <p style="margin:0;font-size:7pt;text-transform:uppercase;letter-spacing:0.12em;color:${S.muted};font-weight:700;">Facture</p>
          <p style="margin:2px 0 0;font-size:14pt;font-weight:800;color:${S.ink};">${escapePdfHtml(invoice.numero)}</p>
          <p style="margin:4px 0 0;font-size:7.5pt;color:${S.muted};">Émise le ${formatPdfDate(invoice.dateCreation)}</p>
          <span style="display:inline-block;margin-top:6px;padding:4px 10px;border-radius:6px;background:${statusBg};color:${statusFg};font-size:7.5pt;font-weight:700;">${statusLabel}</span>
        </div>
      </div>

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px;">
        <div style="padding:8px 10px;border:1px solid ${S.border};border-radius:6px;">
          <p style="margin:0 0 4px;font-size:7pt;text-transform:uppercase;letter-spacing:0.1em;color:${S.muted};font-weight:700;">Émetteur</p>
          <p style="margin:0;font-size:9.5pt;font-weight:700;color:${S.ink};">${COMPANY_NAME}</p>
          <p style="margin:3px 0 0;font-size:7.5pt;color:${S.muted};line-height:1.4;">${COMPANY_CONTACT}</p>
        </div>
        <div style="padding:8px 10px;border:1px solid ${S.border};border-radius:6px;text-align:right;">
          <p style="margin:0 0 4px;font-size:7pt;text-transform:uppercase;letter-spacing:0.1em;color:${S.muted};font-weight:700;">${partyLabel}</p>
          <p style="margin:0;font-size:10pt;font-weight:700;color:${S.ink};">${partyName}</p>
          ${invoice.datePaiement && dejaPaye > 0 ? `<p style="margin:4px 0 0;font-size:7.5pt;color:${S.muted};">Paiement : ${formatPdfDate(invoice.datePaiement)}</p>` : ''}
          ${invoice.modePaiement ? `<p style="margin:2px 0 0;font-size:7.5pt;color:${S.muted};">Mode : ${escapePdfHtml(invoice.modePaiement)}</p>` : ''}
        </div>
      </div>

      <div style="margin-bottom:10px;border:1px solid ${S.border};border-radius:6px;overflow:hidden;">
        <div style="padding:6px 10px;background:#f1f5f9;border-bottom:1px solid ${S.border};">
          <span style="font-size:7.5pt;font-weight:700;text-transform:uppercase;color:${S.muted};letter-spacing:0.06em;">${prestationTitle}</span>
        </div>
        <div style="padding:8px 10px;">
          <p style="margin:0;font-size:9.5pt;font-weight:700;color:${S.ink};">${prestationMain}</p>
          ${prestationSub ? `<p style="margin:4px 0 0;font-size:7.5pt;color:${S.muted};line-height:1.35;">${prestationSub}</p>` : ''}
          ${extraRows}
        </div>
        <div style="display:flex;justify-content:flex-end;padding:6px 10px;background:#fafafa;border-top:1px solid ${S.border};">
          <span style="font-size:8pt;color:${S.muted};margin-right:8px;">Montant TTC ligne</span>
          <span style="font-size:10pt;font-weight:800;color:${S.accent};">${fcfa(invoice.montantTTC, 2)} FCFA</span>
        </div>
      </div>

      <div style="display:flex;justify-content:flex-end;margin-bottom:8px;">
        <div style="width:52%;min-width:200px;padding:10px 12px;border:2px solid ${S.accent};border-radius:8px;background:#f8fafc;">
          ${totalsLine('Montant HT', `${fcfa(invoice.montantHT, 2)} FCFA`)}
          ${remiseBlock}
          ${invoice.remise && invoice.montantHTApresRemise ? totalsLine('HT après remise', `${fcfa(invoice.montantHTApresRemise, 2)} FCFA`) : ''}
          ${tvaBlock}
          ${tpsBlock}
          ${totalsLine('Montant TTC', `${fcfa(invoice.montantTTC, 2)} FCFA`, true, S.accent)}
          ${totalsLine('Déjà payé', `${fcfa(dejaPaye, 2)} FCFA`, false, '#15803d')}
          ${totalsLine('Reste à payer', `${fcfa(resteAPayer, 2)} FCFA`, false, resteAPayer > 0.01 ? '#c2410c' : '#15803d')}
        </div>
      </div>

      ${notesBlock && !trip && !expense && !parcelExpedition ? notesBlock : invoice.notes && (trip || expense || parcelExpedition) ? notesBlock : ''}

      <div style="margin-top:10px;padding-top:8px;border-top:1px solid ${S.border};text-align:center;">
        <p style="margin:0;font-size:8.5pt;font-weight:700;color:${S.ink};">${COMPANY_NAME}</p>
        <p style="margin:2px 0 0;font-size:7.5pt;color:${S.muted};">Merci pour votre confiance.</p>
      </div>
    </div>`;
}

