services:
  - type: web
    name: ansar-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DB_SYNCHRONIZE
        value: "false"
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
